In [1]:
import importlib
import numpy as np
import vtoj_siaf
importlib.reload(vtoj_siaf)
from vtoj_siaf import get_vtoj_siaf

**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-034 DOESN'T MATCH THE CURRENT ONLINE VERSION PRDOPSSOC-036
Please consider updating pysiaf, e.g. pip install --upgrade pysiaf or conda update pysiaf


In [2]:
JtoFGS = np.array([[-0.000873067342356,  0.999757625459087,  0.021998233057671],
                   [ 0.003603343153256, -0.021994952998128,  0.999751583464858],
                   [ 0.999993131751562,  0.000952115833223, -0.003583259602304] ])
FGStoJ = JtoFGS.T

In [3]:
v2, v3, v3angle, VtoJ = get_vtoj_siaf(206.464, -697.970, -1.250817132890, FGStoJ)

R_FGStoV = 
 [[-9.26860580e-04  3.40488980e-03  9.99993774e-01]
 [ 9.99761289e-01 -2.18257461e-02  1.00095982e-03]
 [ 2.18290183e-02  9.99755992e-01 -3.38384759e-03]]


In [4]:
print(v2,v3,v3angle)

10.199456896517669 41.166609695167864 0.00968759049556616


In [5]:
print(VtoJ)

[[ 9.99999984e-01  4.94483617e-05  1.99581355e-04]
 [-4.94164188e-05  9.99999982e-01 -1.69080346e-04]
 [-1.99582618e-04  1.69070959e-04  9.99999961e-01]]


In [6]:
###
### Now the SE-20
###

In [7]:
FGStoJ_old = np.array([[ -0.001004440003336,  0.003381458356796,  0.999993778400453],
                       [  0.999999495544289, -0.000000000000039,  0.001004445745864],
                       [  0.000003396491461,  0.999994282853396, -0.003381456651004]])


In [8]:
v2, v3, v3angle, VtoJ = get_vtoj_siaf(206.464, -697.970, -1.250817132890, FGStoJ_old)
print(v2,v3,v3angle)

R_FGStoV = 
 [[-9.26860580e-04  3.40488980e-03  9.99993774e-01]
 [ 9.99761289e-01 -2.18257461e-02  1.00095982e-03]
 [ 2.18290183e-02  9.99755992e-01 -3.38384759e-03]]
-15.89259829381645 -5.181212006578004 -1.2506145513170919


In [9]:
print(VtoJ)

[[ 9.99999997e-01 -7.70494907e-05 -2.51192247e-05]
 [ 7.75793793e-05  9.99761790e-01  2.18256084e-02]
 [ 2.34315890e-05 -2.18256103e-02  9.99761793e-01]]
